module.exports = {
  apps: [{
    name: 'tennis-link',
    script: 'npm',
    args: 'start',
    cwd: '/home/ubuntu/tennis-link-backup',
    instances: 1,
    exec_mode: 'fork',
    autorestart: true,
    max_memory_restart: '512M',
    watch: false,
    env: {
      NODE_ENV: process.env.NODE_ENV || 'production',
      JWT_SECRET: process.env.JWT_SECRET,
      NEXT_SERVER_ACTIONS_ENCRYPTION_KEY: process.env.NEXT_SERVER_ACTIONS_ENCRYPTION_KEY,
      DATABASE_URL: process.env.DATABASE_URL,
      SMTP_HOST: process.env.SMTP_HOST || 'smtpdm.aliyun.com',
      SMTP_PORT: process.env.SMTP_PORT || '465',
      SMTP_SECURE: process.env.SMTP_SECURE || 'true',
      SMTP_USER: process.env.SMTP_USER,
      SMTP_PASS: process.env.SMTP_PASS,
      EMAIL_FROM_NAME: process.env.EMAIL_FROM_NAME || 'TennisLink',
      EMAIL_FROM_ADDRESS: process.env.EMAIL_FROM_ADDRESS,
      NEXT_PUBLIC_DOMAIN: process.env.NEXT_PUBLIC_DOMAIN || 'https://ydtenhub.online',
      ALIPAY_APP_ID: process.env.ALIPAY_APP_ID,
      ALIPAY_SANDBOX: process.env.ALIPAY_SANDBOX || 'false',
      ALIPAY_CERT_MODE: process.env.ALIPAY_CERT_MODE || 'false',
      ALIPAY_PRIVATE_KEY: process.env.ALIPAY_PRIVATE_KEY,
      ALIPAY_ALIPAY_PUBLIC_KEY: process.env.ALIPAY_ALIPAY_PUBLIC_KEY,
      ALIPAY_GATEWAY: process.env.ALIPAY_GATEWAY || 'https://openapi.alipay.com/gateway.do',
      ALIPAY_NOTIFY_URL: process.env.ALIPAY_NOTIFY_URL || 'https://ydtenhub.online/api/payments/notify/alipay',
      DEFAULT_PAYMENT_METHOD: process.env.DEFAULT_PAYMENT_METHOD || 'alipay',
      ENABLE_PAYMENT: process.env.ENABLE_PAYMENT || 'true',
      SECURE_COOKIES: process.env.SECURE_COOKIES || 'true',
      QWEATHER_API_KEY: process.env.QWEATHER_API_KEY,
      COS_SECRET_ID: process.env.COS_SECRET_ID,
      COS_SECRET_KEY: process.env.COS_SECRET_KEY,
      COS_BUCKET: process.env.COS_BUCKET || 'tennis-link-uploads-1350753429',
      COS_REGION: process.env.COS_REGION || 'ap-shanghai',
      COS_DOMAIN: process.env.COS_DOMAIN || 'https://tennis-link-uploads-1350753429.cos.ap-shanghai.myqcloud.com',
      ALIYUN_ACCESS_KEY_ID: process.env.ALIYUN_ACCESS_KEY_ID,
      ALIYUN_ACCESS_KEY_SECRET: process.env.ALIYUN_ACCESS_KEY_SECRET,
      ALIYUN_SMS_TEMPLATE_CODE: process.env.ALIYUN_SMS_TEMPLATE_CODE || 'SMS_331565516',
      ALIYUN_SMS_SIGN_NAME: process.env.ALIYUN_SMS_SIGN_NAME || '上海跃动智汇体育科技',
    },
    log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    error_file: '/home/ubuntu/tennis-link-backup/logs/pm2-error.log',
    out_file: '/home/ubuntu/tennis-link-backup/logs/pm2-out.log',
    merge_logs: true,
  }]
};
